### ISSUE TITLE
给它发的所有消息都不响应

### ISSUE THREAD

**Issue by geol** [CikeyQi/gpti-plugin#10]
不管是对方还是绘图，都没有任何反应。后台可以看到绘画会提醒要设置密钥。

**Comment by geol** [comment]
不是对方，是对话

**Comment by CikeyQi** [comment]
我们在本地测试中未发现问题，请提供完整的日志以便我们复现问题

**Comment by geol** [comment]
> 我们在本地测试中未发现问题，请提供完整的日志以便我们复现问题

刚刚试了一下，莫得问题了，谢谢😘
