### ISSUE TITLE
使用dalle画图经常因为图片过大导致无法发送

### ISSUE THREAD

**Issue by SnowryFox** [CikeyQi/gpti-plugin#2]
如图，使用的是trss-yunzai搭配comwechat，看别的插件issue好像也有提到过这件事的
![mmexport1705576094101](https://github.com/CikeyQi/gpti-plugin/assets/88602057/2bc56f56-478f-4e36-997e-84908a97cf07)

**Comment by SnowryFox** [comment]
补充dalle mini会发一堆乱七八糟的东西
![mmexport1705576789573](https://github.com/CikeyQi/gpti-plugin/assets/88602057/5ffd03c7-25eb-4fe3-97c3-89ad461af684)
![mmexport1705576789573](https://github.com/CikeyQi/gpti-plugin/assets/88602057/9c18a11e-c7d3-4b59-b687-9582b7b5dc02)

**Comment by CikeyQi** [comment]
这是应用端限制，插件本身无法进行处理

**Comment by CikeyQi** [comment]
插件在QQ测试已通过，未能复现异常问题
