### ISSUE TITLE
请降级 `gpti` 依赖降级到 `2.1.3` 版本，使用命令 `pnpm add gpti@2.1.3`

### ISSUE THREAD

**Issue by A-Kevin1217** [CikeyQi/gpti-plugin#9]
请降级 `gpti` 依赖降级到 `2.1.3` 版本，使用命令 `pnpm add gpti@2.1.3`

_Originally posted by @CikeyQi in https://github.com/CikeyQi/gpti-plugin/issues/8#issuecomment-2190510635_

**Comment by A-Kevin1217** [comment]
按照你给你的方法，依旧还会报错

**Comment by CikeyQi** [comment]
降级到 `2.1.2` 版本试试，我也不清楚最近更新了什么内容

**Comment by A-Kevin1217** [comment]
> pnpm add gpti@2.1.3

试了，不行，我直接装1.0.0都不行

**Comment by CikeyQi** [comment]
我已经自行测试过，使用 `pnpm add gpti@2.1.3` 降级到 `2.1.3` 版本后是启动没有报错且功能完全可用的，请自行确认自己命令是否正确执行，仔细检查无误后再反馈
![image](https://github.com/CikeyQi/gpti-plugin/assets/61369914/bc3a5b08-3601-49ca-a7b4-7d48a3fa9f7c)
